name: boltz
description: A dart/flutter library for boltz swaps
version: 0.2.0
homepage: https://github.com/SatoshiPortal/boltz-dart

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_rust_bridge: ">2.8.0 <=2.9.0"
  ffi: ^2.1.3
  meta: ^1.8.0
  uuid: ^4.1.0
  dio: ^5.4.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1
  archive: ^4.0.5
  http: ^1.2.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ffigen: ^16.1.0
  test: ^1.24.3
  build_runner: ^2.4.6
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  crypto: ^3.0.3
  integration_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
