name: boltz_dart
description: A dart/flutter library for boltz swaps
version: 0.1.6
homepage: https://github.com/SatoshiPortal/boltz-dart

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_rust_bridge: 2.0.0
  ffi: ^2.0.1
  meta: ^1.8.0
  uuid: ^4.1.0
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  archive: ^3.4.10
  http: ^1.2.0
  web_socket_channel: ^2.1.0
  # rust_lib_boltz_dart:
  #   path: rust_builder

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  ffigen: ^9.0.1
  test: ^1.24.3
  build_runner: ^2.4.6
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  crypto: ^3.0.3
  integration_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
